# Generated by Django 2.1.2 on 2018-10-26 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('huobi', '0002_kline_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='kline',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticker',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
